apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stream-app
  labels:
    app: iot-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iot-demo
        name: stream-app
    spec:
      containers:
        - name: stream-app
          image: strimzilab/stream-app:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: "my-cluster-kafka:9092"
            - name: TOPIC_TEMPERATURE
              value: "iot-temperature"
            - name: TOPIC_TEMPERATURE_MAX
              value: "iot-temperature-max"
            - name: TEMPERATURE_THRESHOLD
              value: "20"
            - name: TEMPERATURE_WINDOW_SIZE
              value: "5"